# Default Kibana configuration for docker target
server.name: kibana
server.host: "0"
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
monitoring.ui.container.elasticsearch.enabled: true
elastalertKibanaPlugin.serverSsl: false
elastalertKibanaPlugin.serverHost: elastalert
elastalertKibanaPlugin.serverPort: 3030