version: "3"
services:

  elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    hostname: elasticsearch
    volumes:
      - ../data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g
      cluster.initial_master_nodes: elasticsearch
    ports:
      - 9200:9200
    restart: always
    networks: 
      - log-monitor
    logging:
      options:
        max-file: "5"
        max-size: "1g"

  kibana:
    build:
      context: ./build/kibana
      dockerfile: kibana.dockerfile
      args:
        KIBANA_VERSION: "7.16.2"
    container_name: kibana
    hostname: kibana
    volumes:
      - ./config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    restart : always
    networks:
      - log-monitor
    logging:
      options:
        max-file: "5"
        max-size: "1g"

# reference: https://github.com/johnsusek/praeco
  elastalert-server:
    image: praecoapp/elastalert-server:20210517
    container_name: elastalert-server
    hostname: elastalert-server
    ports: 
      - 3030:3030
      - 3333:3333
    volumes:
      - ./config/elastalert-server/elastalert.config.yaml:/opt/elastalert/config.yaml
      - ./config/elastalert-server/api.config.json:/opt/elastalert-server/config/config.json
      - ../data/elastalert-server/rules:/opt/elastalert/rules
    networks:
      - log-monitor
    depends_on:
      - elasticsearch
    restart : always
    
  curator:
    build:
      context: ./build/curator
      dockerfile: curator.dockerfile
      args:
        CURATOR_VERSION: 5.7
    container_name: curator
    hostname: curator
    networks:
      - log-monitor
    restart : always
    depends_on:
      - elasticsearch
    volumes:
      - ./config/curator:/config    
  
networks:
  log-monitor:
    driver: bridge